image: ubuntu
stack: node 10

environment:
  firebase_deploy_token:
    secure: RGcN1DPrAc+fS4uY8Xp5oGnlJ5+R7/00AcGpSdZphZ4fTq1t6PCOp1skRR78mm2t
  decrypt_service_account_secret:
    secure: V242ykFUloKUEyQFCTk+46ZwFB7tqYXd5RyOHniYEPs=

install:
  - npm i -g firebase-tools
  - npm i --prefix ./functions

build_script:
  - echo $APPVEYOR_BUILD_VERSION > public/version.txt && date --rfc-3339=seconds >> public/version.txt
  - firebase deploy --token $firebase_deploy_token
