image: ubuntu
stack: node 10

environment:
  firebase_deploy_token:
    secure: K6wzWWMje5vzt7KFFyjNpbR+5KzFnWAvjK8JbGa9rktPRGmndeYlWDKDMzfhBOc9

install:
  - npm i -g firebase-tools
  - npm i --prefix ./functions

build_script:
  - echo $APPVEYOR_BUILD_VERSION > public/version.txt && date --rfc-3339=seconds >> public/version.txt
  - firebase deploy --token $firebase_deploy_token
